# Introduction

First of all, to be honest, the title should be 'k-fold cross validation from scratch python **straightforward**' since I code this in hurry for an assignment

So, this is a piece of code from an assignment of mine. I code this by myself by implementing the concept I understand about k-fold cross validation. I'm still learning, so dont expect this will be a good code

For example in this case, I'll use Iris Dataset

# preparation

import function that will be needed to manage the dataset and load the dataset

In [5]:
import numpy as np
import pandas as pd

In [6]:
#read csv
df = pd.read_csv("Iris.csv")                                    
df = df.rename(columns={"Species": "Label"})                    

df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Label
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

# randomizing

because we want to do cross validation using k-fold and do the train and test process with the method we already choose, then we need to randomize the dataset **if the dataset is in ordered form** or just do the randomization part to make sure its randomized completely

In [7]:
df = df.reindex(np.random.permutation(df.index))                                                          
print("Randomized data by randomizing the index : ")

df

Randomized data by randomizing the index :

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Label
123,124,6.3,2.7,4.9,1.8,Iris-virginica
110,111,6.5,3.2,5.1,2.0,Iris-virginica
19,20,5.1,3.8,1.5,0.3,Iris-setosa
72,73,6.3,2.5,4.9,1.5,Iris-versicolor
17,18,5.1,3.5,1.4,0.3,Iris-setosa
...,...,...,...,...,...,...
18,19,5.7,3.8,1.7,0.3,Iris-setosa
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
0,1,5.1,3.5,1.4,0.2,Iris-setosa
111,112,6.4,2.7,5.3,1.9,Iris-virginica
7,8,5.0,3.4,1.5,0.2,Iris-setosa

as you can see, the dataset is completely randomized by now. then to make it easy to split the dataset, then we need to reset the index

In [8]:
df = df.reset_index(drop=True)                                                                                   
print("Randomized data with reseted index: ")

df

Randomized data with reseted index:

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Label
0,124,6.3,2.7,4.9,1.8,Iris-virginica
1,111,6.5,3.2,5.1,2.0,Iris-virginica
2,20,5.1,3.8,1.5,0.3,Iris-setosa
3,73,6.3,2.5,4.9,1.5,Iris-versicolor
4,18,5.1,3.5,1.4,0.3,Iris-setosa
...,...,...,...,...,...,...
145,19,5.7,3.8,1.7,0.3,Iris-setosa
146,61,5.0,2.0,3.5,1.0,Iris-versicolor
147,1,5.1,3.5,1.4,0.2,Iris-setosa
148,112,6.4,2.7,5.3,1.9,Iris-virginica
149,8,5.0,3.4,1.5,0.2,Iris-setosa

now the index has been reset into ordered, and we have randomized dataset

# folds

now, we will make the folds. the code I'll write after this is spliting the dataset into folds manually, by counting and splitting one by one.

you can choose how many folds do you need to do validation (5 or 10 usually). if you're doing this manually like I did, then you need to count the index by yourself and make sure every folds **have the same size or ammount of data**

you can upgrade the code I write by myself with iteration or else

In [9]:
#folds                                                              
fold1 = df.loc[0:29]                                            
fold2 = df.loc[30:59]
fold3 = df.loc[60:89]
fold4 = df.loc[90:119]
fold5 = df.loc[120:149]

# train test validation preparation

now, we will make the train and test dataframe. the code I'll write after this is combining the folds manually to make train and test dataframe for validation

the ammount of train and test dataframe for validation you need for each, is the ammount of folds you have. if you have 5 folds, then you have 5 train dataframe and 5 test dataframe, which makes you have 10 in total. if you 10 folds, then you have 10 train and 10 test dataframe and total 20. and so on....

make sure you input each one correctly

In [10]:
train_val1 = pd.concat([fold1, fold2, fold3, fold4])
test_val1 = fold5

train_val2 = pd.concat([fold1, fold2, fold3, fold5])
test_val2 = fold4

train_val3 = pd.concat([fold1, fold2, fold4, fold5])
test_val3 = fold3

train_val4 = pd.concat([fold1, fold3, fold4, fold5])
test_val4 = fold2

train_val5 = pd.concat([fold2, fold3, fold4, fold5])
test_val5 = fold1

and now here's the code to check the dataframe that has been made

In [11]:
train_val4

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Label
0,124,6.3,2.7,4.9,1.8,Iris-virginica
1,111,6.5,3.2,5.1,2.0,Iris-virginica
2,20,5.1,3.8,1.5,0.3,Iris-setosa
3,73,6.3,2.5,4.9,1.5,Iris-versicolor
4,18,5.1,3.5,1.4,0.3,Iris-setosa
...,...,...,...,...,...,...
145,19,5.7,3.8,1.7,0.3,Iris-setosa
146,61,5.0,2.0,3.5,1.0,Iris-versicolor
147,1,5.1,3.5,1.4,0.2,Iris-setosa
148,112,6.4,2.7,5.3,1.9,Iris-virginica
149,8,5.0,3.4,1.5,0.2,Iris-setosa

In [12]:
test_val4

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Label
30,51,7.0,3.2,4.7,1.4,Iris-versicolor
31,14,4.3,3.0,1.1,0.1,Iris-setosa
32,31,4.8,3.1,1.6,0.2,Iris-setosa
33,100,5.7,2.8,4.1,1.3,Iris-versicolor
34,99,5.1,2.5,3.0,1.1,Iris-versicolor
35,26,5.0,3.0,1.6,0.2,Iris-setosa
36,75,6.4,2.9,4.3,1.3,Iris-versicolor
37,28,5.2,3.5,1.5,0.2,Iris-setosa
38,74,6.1,2.8,4.7,1.2,Iris-versicolor
39,56,5.7,2.8,4.5,1.3,Iris-versicolor
40,32,5.4,3.4,1.5,0.4,Iris-setosa
41,107,4.9,2.5,4.5,1.7,Iris-virginica
42,131,7.4,2.8,6.1,1.9,Iris-virginica
43,66,6.7,3.1,4.4,1.4,Iris-versicolor
44,148,6.5,3.0,5.2,2.0,Iris-virginica
45,54,5.5,2.3,4.0,1.3,Iris-versicolor
46,45,5.1,3.8,1.9,0.4,Iris-setosa
47,130,7.2,3.0,5.8,1.6,Iris-virginica
48,37,5.5,3.5,1.3,0.2,Iris-setosa
49,25,4.8,3.4,1.9,0.2,Iris-setosa
50,125,6.7,3.3,5.7,2.1,Iris-virginica
51,30,4.7,3.2,1.6,0.2,Iris-setosa
52,116,6.4,3.2,5.3,2.3,Iris-virginica
53,108,7.3,2.9,6.3,1.8,Iris-virginica
54,143,5.8,2.7,5.1,1.9,Iris-virginica
55,114,5.7,2.5,5.0,2.0,Iris-virginica
56,64,6.1,2.9,4.7,1.4,Iris-versicolor
57,102,5.8,2.7,5.1,1.9,Iris-virginica
58,134,6.3,2.8,5.1,1.5,Iris-virginica
59,109,6.7,2.5,5.8,1.8,Iris-virginica

# the validation process

the validation process itself is to implement the machine learning or deep learning with the train dataset and test it with the test dataset

# conclusion

so for the conclusion

here's the main steps to make your own k-fold cross validation dataframe/dataset
1. preparation (load the dataset)
2. randomizing (the dataset)
3. make the folds
4. make the train and test dataframe
and after doing that, you can implement your train and test dataframe for validation with k-fold cross validation method

and here's tips from me
* please upgrade the code yourself to be better than mine for your own project

Thank you for reading